Repository wecode-bootcamp-korea/29-1st-FRESH-EZ-frontend, pull requests merged in 2022-02, with the labels that each got.

#15 [29기 이주미] Footer : 100% 구현
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: Status: 리뷰 요청

#11 [29기 박경원] Add: feature/SubsOpt 구독옵션 선택 모달창
  src/Router.js
  src/pages/SubsIntro/SubsIntro.js
  src/pages/SubsOpt/SubsDetail.js
  src/pages/SubsOpt/SubsOpt.js
  src/pages/SubsOpt/SubsOpt.scss
  src/pages/SubsOpt/SubsOptData.js
  src/pages/SubsOpt/SubsOptForm.js
  src/pages/SubsOpt/SubsOptPred.js
  src/pages/SubsOpt/SubsOptPredServerCalc.js
  src/pages/SubsOpt/SubsOptQuery.js
  src/pages/SubsOpt/SubsOptSelect.js
  src/pages/SubsOpt/SubsOptServeCalc.js
  src/pages/SubsOpt/SubsOptStepBtn.js
  src/pages/SubsOpt/SubsStep.js
  src/pages/SubsSelect/SubsSelect.js
Labels: Status: 리뷰 요청

#13 [29기 곽승현] 구독 상세 페이지의 룩 구현
  src/Router.js
  src/pages/SubsDetail/Data.json
  src/pages/SubsDetail/SubsDetail.js
  src/pages/SubsDetail/SubsDetail.scss
  src/pages/SubsSelect/SubsSelect.js
  src/styles/common.scss
Labels: Status: Accepted

#8 [29기 이주미] Loign : 구현완료 (전체 머지 후 링크만 걸면 진짜 완성)
  public/images/checked.png
  public/images/onlyLogo.png
  src/Router.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: Status: Accepted

#2 [29기 박경원] Add : feature/SubsList 구독 상품 리스트 페이지
  public/data/SUBSLIST_DATA.json
  public/images/SubsIntro/ Readme.md
  public/images/SubsList/bento.png
  public/images/SubsList/meal.png
  public/images/SubsList/salad.png
  public/images/SubsList/sandwich.png
  src/Router.js
  src/pages/SubsList/SubsList.js
  src/pages/SubsList/SubsList.scss
  src/pages/SubsList/SubsProd.js
  src/pages/SubsList/SubsProd.scss
Labels: Status: Accepted

#17 [29기 이주미] Footer : 100% 구현완료
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: Status: 리뷰 요청

#18 [29기 이주미] Login : 100% 완료
  public/images/Login/minibanner.png
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: Status: 리뷰 요청

#9 [29기 이주미] SignUp : 100% 구현완료
  public/images/SignUp/minibanner.png
  src/Router.js
  src/pages/Login/Login.scss
  src/pages/Main/Main.scss
  src/pages/SignUp/PreSignUp.js
  src/pages/SignUp/PreSignUp.scss
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
Labels: Status: Conflict 해결 요청

#16 [29기 곽승현 ] Add : 구독 상품 버튼에 따라, 각각 다른 구독 상세 페이지가 렌더링 되도록 동적 라우팅을 구현했습니다.
  public/data/SUBS_CATEGORY.json
  public/images/SubsDetail/subscriptionDetail1.jpg
  public/images/SubsDetail/subscriptionDetail2.jpg
  public/images/SubsDetail/subscriptionDetail3.jpg
  src/Router.js
  src/pages/SubsDetail/Data.json
  src/pages/SubsDetail/SubsDetail.js
  src/pages/SubsSelect/Button.js
  src/pages/SubsSelect/SubsSelect.js
Labels: Status: Conflict 해결 요청

#5 [29기 곽승현] Add : 단품 구매 상품 목록 페이지의 룩을 구현하고, 컴포넌트를 나누고 mock data를 적용했습니다
  public/data/PRODUCT_DATA.json
  public/data/SUB_CATEGORY.json
  src/Router.js
  src/pages/Details/Details.js
  src/pages/ProductList/ProductAll.js
  src/pages/ProductList/ProductAll.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/components/CategoryButton.js
  src/pages/ProductList/components/CategoryButton.scss
  src/pages/ProductList/components/PaginationButton.js
  src/pages/ProductList/components/PaginationButton.scss
  src/pages/ProductList/components/ProductCard.js
  src/pages/ProductList/components/ProductCard.scss
  src/pages/ProductList/components/ProductList.js
  src/pages/ProductList/components/ProductList.scss
  src/styles/variables.scss
Labels: Status: 리뷰 요청

#6 [29기 정수진] Feature/details
  public/data/recommendData.json
  public/images/Details/SingleDescriptionSalad.jpg
  public/images/Details/salad_test.jpg
  src/Router.js
  src/pages/Details/AdditionalOptionList.js
  src/pages/Details/Details.js
  src/pages/Details/Details.scss
  src/pages/Details/SelectedProduct.js
  src/pages/Details/SelectionOptionList/SelectionOptionList.js
  src/pages/Details/SelectionOptionList/SelectionOptionList.scss
  src/pages/Details/SizeModal.js
  src/pages/Details/SuggestionsWrap.js
  src/pages/Details/additionalOptions.js
  src/pages/Details/recommendData.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중
